#!/usr/bin/env bash
# Stage A of docs/layout-variants.md: survey maps in game, once each.
#
# Boots a headless server, waits for the nav mesh to be decorated, dumps the
# engine's own area graph + hull validity + objective entity inventory to
# game/insurgency/surveys/<map>.json, then changelevels to the next map and
# does it again. One batch per map version; after that the analysis in
# packages/ never needs a server.
#
# The whole reason this runs in game rather than offline: the shipped .nav
# parses with a truncated connection graph, and five of the subscribed
# workshop maps ship no .nav at all. See docs/layout-variants.md §4A.
#
#   tools/survey.sh ministry_coop
#   tools/survey.sh --workshop                 # every subscribed map with a .bsp
#   tools/survey.sh --vis ministry_coop        # also export the visibility matrix
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
. "$root/tools/steam-paths.sh"

vis=0
# Seconds after map start before dumping. The mesh is decorated some way into
# the load and a big map takes longer: toujane_b2 is a 311 MB BSP and read 0
# areas at 12 s. MM_SURVEY_DELAY raises it for a batch that needs it.
delay="${MM_SURVEY_DELAY:-12.0}"
maps=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --vis)      vis=1; shift ;;
    --workshop)
      ws="${WORKSHOP:-$(steam_workshop_roots 222880)}"
      [[ -d "$ws" ]] || { echo "no workshop content at $ws" >&2; exit 1; }
      while IFS= read -r b; do maps+=("$(basename "$b" .bsp)"); done \
        < <(find "$ws" -name '*.bsp' | sort)
      shift ;;
    --coop)
      while IFS= read -r b; do maps+=("$(basename "$b" .bsp)"); done \
        < <(find "$root/game/insurgency/maps" -maxdepth 1 -name '*_coop.bsp' | sort)
      shift ;;
    *) maps+=("$1"); shift ;;
  esac
done

[[ ${#maps[@]} -gt 0 ]] || {
  echo "usage: survey.sh [--vis] [--workshop|--coop] <map>..." >&2; exit 1; }

game="$root/game/insurgency"
[[ -d "$game/addons/sourcemod" ]] || {
  echo "SourceMod is not installed - run tools/fetch-sourcemod.sh" >&2; exit 1; }
[[ -f "$game/addons/sourcemod/plugins/disabled/mapmaker_survey.smx" ]] || {
  echo "survey plugin is not built - run tools/build-plugins.sh" >&2; exit 1; }

mkdir -p "$game/surveys" "$game/cfg"

# The rotation goes in a file, not in the cfg. The plugin advances the map
# itself and so has to read the list back, but the engine tokenises a console
# command into a 512-byte buffer: `mm_survey_list "<34 workshop maps>"` is 597
# bytes and simply never arrives, leaving the cvar empty and the batch stopped
# after its first map with nothing in the log. One name per line has no limit.
cat > "$game/cfg/mapmaker_survey.cfg" <<CFG
// Generated by tools/survey.sh - edits here are overwritten.
hostname "mapmaker survey"
sv_lan 1
sv_pure 0
mp_autoteambalance 0
bot_quota 0
mp_timelimit 0
mp_warmup_enabled 0

// The survey runs on an empty server, and an empty Source server hibernates:
// it stops simulating entirely, so no SourceMod timer ever fires and the dump
// never happens. Nothing in the log says so - the server just sits there.
sv_hibernate_when_empty 0
sv_hibernate_postgame_delay 0

sm plugins load disabled/mapmaker_survey

mm_survey_auto 1
mm_survey_vis ${vis}
mm_survey_delay ${delay}
mm_survey_out "surveys"
mm_survey_list_file "cfg/mapmaker_survey_list.txt"
mm_survey_quit 1
CFG

printf '// Generated by tools/survey.sh - edits here are overwritten.\n' \
  > "$game/cfg/mapmaker_survey_list.txt"
printf '%s\n' "${maps[@]}" >> "$game/cfg/mapmaker_survey_list.txt"

echo "surveying ${#maps[@]} map(s), starting at ${maps[0]}"
echo "output -> $game/surveys/"
echo

exec "$root/tools/srcds.sh" --service survey --map "${maps[0]}" \
  --players 1 --cfg mapmaker_survey.cfg
